name: Elijah Dou'Blog
author: Elijah Dou
baseurl: ""
description: for iOS techniques and so on.
github: https://github.com/elijahdou
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: elijahdou@gmail.com
location: 42°2'16"N   70°12'47"W
disqus: elijahdou

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# setting for analytics helper
#analytics :
#  provider : google
#  google : 
#      tracking_id : 'UA-64460072-1'
analytics: 
    provider: custom

# 多说评论
comments :
  provider : duoshuo
  duoshuo :
    short_name : elijahdou
  disqus :
      short_name : elijahdou
      