markdown:         rdiscount
pygments:         true
paginate:         4

title:            Elijah Dou'Blog
url:              http://elijahdou.github.io
feed:             /atom.xml
author:
    name:         Elijah Dou
    email:        elijahdou@gmail.com
    description:  "This is a blog maintained by elijah dou for iOS techniques and so on."

about:            "一个睡不醒的宅男，喜爱篮球、动漫、音乐；喜欢DIY但是水平低洼的不行。"
follow:
    email:        elijahdou@gmail.com
    github:       https://github.com/elijahdou
    twitter:      http://www.twitter.com
    google:       https://www.google.com/
    facebook:     http://facebook.com
description:      Just another blog theme -- the One

indexContent:     true
imageLink:        http://www.pizn.net/static/images/20121109Monutain.jpg


style:            /css/style.css
blogName:         theOne 
blogDesc:         This is a blog maintained by elijah dou for iOS techniques and so on.
favicon:          /favicon.ico
theme:            default

#disqus:           elijahdou

copyright:        Copyright © 2011-2012 PIZn All rights reserved.
test:             ok

# setting for analytics helper
#analytics :
#  provider : google
#  google : 
#      tracking_id : 'UA-64460072-1'
analytics: 
    provider: custom

# 多说评论
comments :
  provider : duoshuo
  duoshuo :
    short_name : elijahdou
  disqus :
      short_name : elijahdou
