markdown:         rdiscount
pygments:         true
paginate:         5

title:            Elijah   #Elijah Dou'Blog
url:              http://elijahdou.github.io
feed:             /atom.xml
author:
    name:         Elijah Dou
    email:        elijahdou@gmail.com
    description:  "for iOS techniques and so on"

about:            "一个睡不醒的宅男，喜爱篮球、动漫、音乐；喜欢DIY但是水平低洼的不行。"
follow:
    email:        elijahdou@gmail.com
    github:       https://github.com/elijahdou
    twitter:      http://www.twitter.com
    google:       https://www.google.com/
    facebook:     http://facebook.com
description:      for iOS techniques and so on

indexContent:     true
imageLink:        http://cul.shangdu.com/recommend/2010/20150801/P_6014141_1__1738307735.jpg


style:            /css/style.css
blogName:         Elijah  #Elijah Dou'Blog
blogDesc:         for iOS techniques and so on
favicon:          /favicon.ico
theme:            green  # default red,green,blue,pink,drown

disqus:           elijahdoublog

copyright:        Copyright © 2015-2027 ElijahDou All rights reserved.
#test:             ok
# 配置详见：http://www.zhanxin.info/jekyll/2012-11-14-the-one-theme.html

# setting for analytics helper
#analytics :
#  provider : google
#  google : 
#      tracking_id : 'UA-64460072-1'
analytics: 
    provider: custom

# 多说评论
#comments :
#  provider : duoshuo
#  duoshuo :
#    short_name : elijahdou
#  disqus :
#      short_name : elijahdou
